name: Publish Production Images

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: "Docker meta (alpine-php-cli)"
        id: alpine-php-cli-meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/cbaskauskas/alpine-php-cli
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
          flavor: |
            latest=true
      -
        name: "Docker meta (alpine-php-fpm)"
        id: alpine-php-fpm-meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/cbaskauskas/alpine-php-fpm
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
          flavor: |
            latest=true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push alpine-php-fpm
        uses: docker/build-push-action@v2
        with:
          context: ../
          file: fpm/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.alpine-php-fpm-meta.outputs.tags }}
          labels: ${{ steps.alpine-php-fpm-meta.outputs.labels }}
          no-cache: true
      -
        name: Build and push alpine-php-cli
        uses: docker/build-push-action@v2
        with:
          context: ../
          file: cli/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.alpine-php-cli-meta.outputs.tags }}
          labels: ${{ steps.alpine-php-cli-meta.outputs.labels }}
          no-cache: true
